- name: Test
  hosts: all
  tasks:
    - name: python-pi is present
      apt:
        name: python-pip
        state: present
      become: true

    - name: Docker-py is present
      pip: name=docker-py state=present
      become: true

    - name: Docker Login
      docker_login:
        username: jamfac
        email: "{{ docker_hub_email }}"
        password: "{{ docker_hub_password }}"

    - name: Directory for Node-Red Data
      file:
        path: /home/pi/NODE-RED-DATA
        mode: 0777
        state: directory

    - name: Stop Nodered
      docker_container:
        name: nodered
        image: jamfac/rpi-node-red
        state: stopped

    - name: Enable projects in Nodered
      copy:
        src: settings.js
        dest: /home/pi/NODE-RED-DATA/settings.js

    - name: Start Nodered
      docker_container:
        name: nodered
        image: jamfac/rpi-node-red
        state: started
        detach: true
        ports:
          - "1880:1880"
        volumes:
          - "/home/pi/NODE-RED-DATA:/data"
          - "/home/pi:/home"
        devices:
          - "/dev/video0"
