- name: Test
  hosts: all
  tasks:
    - name: python-pi is present
      apt:
        name: python-pip
        state: present
      become: true

    - name: Docker-py is present
      pip: name=docker-py state=present
      become: true

    - name: Application container
      docker_container:
        name: nodered
        image: jamfac/rpi-node-red
        state: started
        detach: true
        ports:
          - "1880:1880"
        volumes:
          - "/home/pi/NODE-RED-DATA:/data"
          - "/home/pi:/home"
        devices:
          - "/dev/video0"
